# Generated by Django 4.2.3 on 2023-07-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_involvement_is_manager_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvement',
            name='function',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.function'),
        ),
    ]
