---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/projects":
    get:
      summary: list projects
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create project
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              example:
                id: 1
                created_at: '2023-10-22T12:23:56.815Z'
                updated_at: '2023-10-22T12:23:56.815Z'
                title: ProjIFRN Title
                description: ProjIFRN description project
                content: content
                status: in_progress
                name: ProjIFRN
                external_url: htts://
                short_description: ProjIFRN short description
                keywords: corporative
                start_at: '2023-09-22T12:23:56.799Z'
                end_at: '2023-11-22T12:23:56.800Z'
                phase: distributed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                description:
                  type: string
                content:
                  type: string
                status:
                  type: integer
                external_url:
                  type: string
                short_description:
                  type: string
                keywords:
                  type: string
                star_at:
                  type: datetime
                end_at:
                  type: datetime
                phase:
                  type: integer
  "/projects/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show project
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                created_at: '2023-10-22T12:23:56.821Z'
                updated_at: '2023-10-22T12:23:56.821Z'
                title: ProjIFRN Title
                description: ProjIFRN description project
                content: content
                status: in_progress
                name: ProjIFRN
                external_url: htts://
                short_description: ProjIFRN short description
                keywords: corporative
                start_at: '2023-09-22T12:23:56.821Z'
                end_at: '2023-11-22T12:23:56.821Z'
                phase: distributed
    put:
      summary: update project
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                created_at: '2023-10-22T12:23:56.828Z'
                updated_at: '2023-10-22T12:23:56.832Z'
                title: ProjIFRN Title
                description: ProjIFRN description project
                content: content
                status: in_progress
                name: ProjIFRN
                external_url: htts://
                short_description: ProjIFRN short description
                keywords: corporative
                start_at: '2023-09-22T12:23:56.828Z'
                end_at: '2023-11-22T12:23:56.828Z'
                phase: distributed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                description:
                  type: string
                content:
                  type: string
                status:
                  type: integer
                external_url:
                  type: string
                short_description:
                  type: string
                keywords:
                  type: string
                star_at:
                  type: datetime
                end_at:
                  type: datetime
    delete:
      summary: delete project
      responses:
        '204':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
