# Generated by Django 4.2.1 on 2023-05-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='user_profile/type_media/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='type_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.typemedia'),
        ),
    ]
