# Generated by Django 4.2.1 on 2023-05-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_typemedia_remove_socialmedia_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biografy',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
