# Generated by Django 4.2.2 on 2023-07-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description', models.CharField(blank=True, default=' ', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', upload_to='proj/img/%Y/%m/%d/')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=150)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='em_andamento', max_length=20)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj.category')),
                ('keyword', models.ManyToManyField(to='proj.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField(blank=True, default=None, null=True)),
                ('function', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='proj.function')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proj.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
