# Generated by Django 4.2.2 on 2023-07-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
