# Generated by Django 4.2.1 on 2023-05-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_alter_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, default=' ', upload_to='proj/img/%Y/%m/%d/'),
        ),
    ]
