# Generated by Django 4.2.1 on 2023-05-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_alter_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvement',
            name='date_finish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
