# Generated by Django 4.2.1 on 2023-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_alter_involvement_date_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.ManyToManyField(to='proj.keyword'),
        ),
    ]
