# Generated by Django 4.2.1 on 2023-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_alter_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='em andamento', max_length=50),
        ),
    ]
