# Generated by Django 4.2.1 on 2023-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='em_andamento', max_length=20),
        ),
    ]
